import { AppType, ConnectionState, PacketAction, reverseTuple, tupleKey } from '../utils/types.js';
export class ConnectionTracker { constructor(id = 0, maxConnections = 100000) { this.id = id; this.maxConnections = maxConnections; this.connections = new Map(); this.totalSeen = 0; this.classifiedCount = 0; this.blockedCount = 0; }
  getOrCreateConnection(tuple) { let c = this.getConnection(tuple); if (c) return c; if (this.connections.size >= this.maxConnections) this.evictOldest(); const now = Date.now(); c = { tuple, state: ConnectionState.NEW, appType: AppType.UNKNOWN, sni: '', packetsIn: 0, packetsOut: 0, bytesIn: 0, bytesOut: 0, firstSeen: now, lastSeen: now, action: PacketAction.FORWARD, synSeen: false, synAckSeen: false, finSeen: false }; this.connections.set(tupleKey(tuple), c); this.totalSeen++; return c; }
  getConnection(tuple) { return this.connections.get(tupleKey(tuple)) ?? this.connections.get(tupleKey(reverseTuple(tuple))) ?? null; }
  updateConnection(c, size, outbound = true) { c.lastSeen = Date.now(); outbound ? (c.packetsOut++, c.bytesOut += size) : (c.packetsIn++, c.bytesIn += size); }
  classifyConnection(c, app, sni = '') { if (c.state !== ConnectionState.CLASSIFIED) this.classifiedCount++; c.appType = app; c.sni = sni; c.state = ConnectionState.CLASSIFIED; }
  blockConnection(c) { if (c.state !== ConnectionState.BLOCKED) this.blockedCount++; c.state = ConnectionState.BLOCKED; c.action = PacketAction.DROP; }
  cleanupStale(timeoutMs = 300000) { const now = Date.now(); let removed = 0; for (const [key, c] of this.connections) if (now - c.lastSeen > timeoutMs || c.state === ConnectionState.CLOSED) { this.connections.delete(key); removed++; } return removed; }
  evictOldest() { let oldest; for (const [key, c] of this.connections) if (!oldest || c.lastSeen < oldest[1].lastSeen) oldest = [key, c]; if (oldest) this.connections.delete(oldest[0]); }
  getAllConnections() { return [...this.connections.values()]; } getStats() { return { activeConnections: this.connections.size, totalConnectionsSeen: this.totalSeen, classifiedConnections: this.classifiedCount, blockedConnections: this.blockedCount }; } }
export class GlobalConnectionTable { constructor(trackers = []) { this.trackers = trackers; } getGlobalStats() { const appDistribution = {}; const domains = new Map(); let totalActiveConnections = 0, totalConnectionsSeen = 0; for (const t of this.trackers) { const s = t.getStats(); totalActiveConnections += s.activeConnections; totalConnectionsSeen += s.totalConnectionsSeen; for (const c of t.getAllConnections()) { appDistribution[c.appType] = (appDistribution[c.appType] ?? 0) + 1; if (c.sni) domains.set(c.sni, (domains.get(c.sni) ?? 0) + 1); } } return { totalActiveConnections, totalConnectionsSeen, appDistribution, topDomains: [...domains.entries()].sort((a,b)=>b[1]-a[1]).slice(0,20).map(([domain,count])=>({domain,count})) }; } }
