import { promises as fs } from 'node:fs';
import { PcapReader, buildPcapBuffer } from './pcapReader.js';
import { PacketParser } from './packetParser.js';
import { FastPathProcessor } from './fastPath.js';
import { RuleManager } from './ruleManager.js';
import { GlobalConnectionTable } from './connectionTracker.js';
import { hashTuple, PacketAction, Protocol } from '../utils/types.js';
export class DPIEngine { constructor(config = {}) { this.config = { numLoadBalancers: 2, fpsPerLoadBalancer: 2, ...config }; this.ruleManager = config.ruleManager ?? new RuleManager(); this.fastPaths = Array.from({ length: this.config.numLoadBalancers * this.config.fpsPerLoadBalancer }, (_, i) => new FastPathProcessor(i, this.ruleManager)); this.globalConnections = new GlobalConnectionTable(this.fastPaths.map((fp) => fp.tracker)); this.stats = { totalPackets: 0, totalBytes: 0, forwardedPackets: 0, droppedPackets: 0, tcpPackets: 0, udpPackets: 0, otherPackets: 0 }; }
  createJob(raw, parsed, packetId) { return { packetId, tuple: { srcIp: parsed.srcIpInt ?? 0, dstIp: parsed.dstIpInt ?? 0, srcPort: parsed.srcPort ?? 0, dstPort: parsed.dstPort ?? 0, protocol: parsed.protocol ?? 0 }, data: raw.data, payload: parsed.payload ?? Buffer.alloc(0), payloadOffset: parsed.payloadOffset, payloadLength: parsed.payloadLength, tcpFlags: parsed.tcpFlags ?? 0, tsSec: raw.header.tsSec, tsUsec: raw.header.tsUsec, parsed }; }
  processJob(job) { const fp = this.fastPaths[hashTuple(job.tuple) % this.fastPaths.length]; const action = fp.process(job); this.stats.totalPackets++; this.stats.totalBytes += job.data.length; if (job.tuple.protocol === Protocol.TCP) this.stats.tcpPackets++; else if (job.tuple.protocol === Protocol.UDP) this.stats.udpPackets++; else this.stats.otherPackets++; action === PacketAction.DROP ? this.stats.droppedPackets++ : this.stats.forwardedPackets++; return { action, fpId: fp.id, job }; }
  async processFile(inputFile, outputFile) { const reader = await new PcapReader().open(inputFile); const rawPackets = await reader.readAllPackets(); const forwarded = []; const packets = []; let packetId = 0; for (const raw of rawPackets) { const parsed = PacketParser.parse(raw); if (!parsed) continue; const job = this.createJob(raw, parsed, ++packetId); const result = this.processJob(job); packets.push({ id: packetId, action: result.action, fpId: result.fpId, tuple: job.tuple, srcIp: parsed.srcIp, dstIp: parsed.dstIp, srcPort: parsed.srcPort, dstPort: parsed.dstPort, protocol: parsed.protocol, payloadLength: parsed.payloadLength, blockReason: job.blockReason ?? null }); if (result.action !== PacketAction.DROP) forwarded.push(raw); } if (outputFile) await fs.writeFile(outputFile, buildPcapBuffer(reader.getGlobalHeader(), forwarded)); return { inputFile, outputFile, pcapHeader: reader.getGlobalHeader(), packets, stats: this.getStats(), report: this.generateReport() }; }
  getStats() { return { ...this.stats, connections: this.globalConnections.getGlobalStats(), fastPaths: this.fastPaths.map((fp) => ({ id: fp.id, ...fp.getStats() })), rules: this.ruleManager.getStats() }; }
  generateReport() { const s = this.getStats(); return { summary: this.stats, applicationDistribution: s.connections.appDistribution, topDomains: s.connections.topDomains, activeConnections: s.connections.totalActiveConnections, totalConnectionsSeen: s.connections.totalConnectionsSeen }; }
}
export const sharedRuleManager = new RuleManager();
