import { AppType, ConnectionState, PacketAction, Protocol, TCPFlags, sniToAppType } from '../utils/types.js';
import { ConnectionTracker } from './connectionTracker.js';
import { DNSExtractor, HTTPHostExtractor, SNIExtractor } from './extractors.js';
export class FastPathProcessor { constructor(id, ruleManager) { this.id = id; this.ruleManager = ruleManager; this.tracker = new ConnectionTracker(id); this.stats = { packetsProcessed:0, packetsForwarded:0, packetsDropped:0, sniExtractions:0, classificationHits:0 }; }
  process(job) { this.stats.packetsProcessed++; const c = this.tracker.getOrCreateConnection(job.tuple); this.tracker.updateConnection(c, job.data.length, true); if (job.tuple.protocol === Protocol.TCP) this.updateTCPState(c, job.tcpFlags); if (c.state === ConnectionState.BLOCKED) return this.count(PacketAction.DROP); if (c.state !== ConnectionState.CLASSIFIED && job.payload?.length) this.inspect(job, c); const reason = this.ruleManager?.shouldBlock({ srcIp: job.tuple.srcIp, dstPort: job.tuple.dstPort, app: c.appType, domain: c.sni }); if (reason) { this.tracker.blockConnection(c); job.blockReason = reason; return this.count(PacketAction.DROP); } return this.count(PacketAction.FORWARD); }
  count(action) { action === PacketAction.DROP ? this.stats.packetsDropped++ : this.stats.packetsForwarded++; return action; }
  inspect(job, c) { const payload = job.payload; const sni = SNIExtractor.extract(payload); if (sni) { this.stats.sniExtractions++; const app = sniToAppType(sni); if (![AppType.UNKNOWN, AppType.HTTPS].includes(app)) this.stats.classificationHits++; this.tracker.classifyConnection(c, app, sni); return; } const host = HTTPHostExtractor.extract(payload); if (host) { const app = sniToAppType(host); if (![AppType.UNKNOWN, AppType.HTTP].includes(app)) this.stats.classificationHits++; this.tracker.classifyConnection(c, app, host); return; } if (job.tuple.dstPort === 53 || job.tuple.srcPort === 53) { const q = DNSExtractor.extractQuery(payload); if (q) this.tracker.classifyConnection(c, AppType.DNS, q); } else if (job.tuple.dstPort === 80) this.tracker.classifyConnection(c, AppType.HTTP); else if (job.tuple.dstPort === 443) this.tracker.classifyConnection(c, AppType.HTTPS); }
  updateTCPState(c, flags) { if (flags & TCPFlags.SYN) (flags & TCPFlags.ACK) ? c.synAckSeen = true : c.synSeen = true; if (c.synSeen && c.synAckSeen && (flags & TCPFlags.ACK) && c.state === ConnectionState.NEW) c.state = ConnectionState.ESTABLISHED; if (flags & TCPFlags.FIN) c.finSeen = true; if ((flags & TCPFlags.RST) || (c.finSeen && (flags & TCPFlags.ACK))) c.state = ConnectionState.CLOSED; }
  getStats() { return { ...this.stats, connectionsTracked: this.tracker.getStats().activeConnections }; }
}
